# Cloud Build configuration for Pattern Discovery Agent A2A Server
# Automates Docker build and Cloud Run deployment

steps:
  # Step 1: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        # Expand Cloud Build substitutions into a concrete env file
        cat > env.yaml <<EOF
        GCP_PROJECT_ID: "${PROJECT_ID}"
        GCP_REGION: "${_REGION}"
        KNOWLEDGE_BASE_REPO: "${_KNOWLEDGE_BASE_REPO}"
        CORS_ORIGINS: "http://localhost:3000,http://localhost:5173,https://*.vercel.app,https://dev-nexus-frontend-noig7bsv5-milan-patels-projects-187b35de.vercel.app"
        USE_POSTGRESQL: "true"
        POSTGRES_HOST: "10.8.0.2"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "devnexus"
        POSTGRES_USER: "devnexus"
        ORCHESTRATOR_URL: "https://architecture-kb-orchestrator-75l7mntama-uc.a.run.app"
        EOF

        # Quote the --set-secrets value to ensure it's passed as a single arg
        gcloud run deploy pattern-discovery-agent \
          --image gcr.io/${PROJECT_ID}/pattern-discovery-agent:latest \
          --region ${_REGION} \
          --platform managed \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --timeout 300 \
          --allow-unauthenticated \
          --vpc-connector projects/${PROJECT_ID}/locations/${_REGION}/connectors/dev-nexus-connector \
          --vpc-egress all-traffic \
          --env-vars-file env.yaml \
          --set-secrets 'GITHUB_TOKEN=GITHUB_TOKEN:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,POSTGRES_PASSWORD=POSTGRES_PASSWORD:latest'

# Substitution variables (can be overridden at build time)
substitutions:
  _REGION: us-central1
  _KNOWLEDGE_BASE_REPO: patelmm79/dev-nexus

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build (10 minutes)
timeout: 600s
