# Cloud Build configuration for Pattern Discovery Agent A2A Server
# Automates Docker build and Cloud Run deployment

steps:
  # Step 1: Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pattern-discovery-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--allow-unauthenticated'  # Change to --no-allow-unauthenticated for production
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$_REGION,KNOWLEDGE_BASE_REPO=$_KNOWLEDGE_BASE_REPO,CORS_ORIGINS=http://localhost:3000,http://localhost:5173,https://*.vercel.app'
      - '--set-secrets'
      - 'GITHUB_TOKEN=GITHUB_TOKEN:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest'

# Substitution variables (can be overridden at build time)
substitutions:
  _REGION: us-central1
  _KNOWLEDGE_BASE_REPO: patelmm79/dev-nexus

# Images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/pattern-discovery-agent:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for entire build (10 minutes)
timeout: 600s
